---
title: "final-task"
author: "Fernando Lordao"
date: "7 de julho de 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r General Configuration}
set.seed(20180707)
```

```{r}
library(tidyverse)
library(lubridate)
library(chron)
library(boot)
library(reshape2)
theme_set(theme_bw())
```

## Descrição geral

Vamos explorar os dados do artigo "A Comparison of 10 Sampling Algorithms for Configurable Systems".


## Carga dos dados

```{r ETL}
bugs = read_csv("../ComparativeStudy/stats.csv")
```

## Plotando quantidade de erros detectada pelos algoritmos

```{r warning=FALSE}
bugs2 <- bugs %>% 
  select(alg_one_enabled, alg_one_disabled, alg_all_enabled_disabled, alg_pair_wise) %>% 
  summarize(alg_one_enabled = sum(alg_one_enabled),
            alg_one_disabled = sum(alg_one_disabled),
            alg_all_enabled_disabled = sum(alg_all_enabled_disabled),
            alg_pair_wise = sum(alg_pair_wise)) %>% 
  melt(id.vars = NULL) %>% 
  mutate(ci_min = NA, ci_max = NA)

bugs2 %>% 
  ggplot(aes(x = variable, y = value)) +
  geom_bar(stat = "identity", fill="red")  +
  labs(title = "Bugs detectados por cada algoritmo",
       x = "algoritmos", y = "quantidade de bugs")
```


## Analisando a média de taxa de cliques diária geral (sem distinção de grupos)

```{r}

fbs_general <- function(data, indexes, algorithm_colname){
  res = data %>% 
    slice(indexes) %>% 
    subset(select = c(algorithm_colname))
  return(sum(res))
}

## One-Enabled
funcao_bootstrap_one_enabled <- function(data, indexes){
  return(fbs_general(data, indexes, "alg_one_enabled"))
}

bootstraps_one_enabled <- boot(data = bugs, 
                   statistic = funcao_bootstrap_one_enabled,
                   R = 2000)

ci_one_enabled = boot.ci(boot.out = bootstraps_one_enabled, conf = 0.95, type = "basic")

bugs2[1, 3] = as.integer(round(ci_one_enabled$basic[4]))
bugs2[1, 4] = as.integer(round(ci_one_enabled$basic[5]))

## One-Disabled
funcao_bootstrap_one_disabled <- function(data, indexes){
  return(fbs_general(data, indexes, "alg_one_disabled"))
}

bootstraps_one_disabled <- boot(data = bugs, 
                   statistic = funcao_bootstrap_one_disabled,
                   R = 2000)

ci_one_disabled = boot.ci(boot.out = bootstraps_one_disabled, conf = 0.95, type = "basic")

bugs2[2, 3] = as.integer(round(ci_one_disabled$basic[4]))
bugs2[2, 4] = as.integer(round(ci_one_disabled$basic[5]))


## All-Enabled-Disabled
funcao_bootstrap_all_enabled_disabled <- function(data, indexes){
  return(fbs_general(data, indexes, "alg_all_enabled_disabled"))
}

bootstraps_all_enabled_disabled <- boot(data = bugs, 
                   statistic = funcao_bootstrap_all_enabled_disabled,
                   R = 2000)

ci_all_enabled_disabled = boot.ci(boot.out = bootstraps_all_enabled_disabled, conf = 0.95, type = "basic")

bugs2[3, 3] = as.integer(round(ci_all_enabled_disabled$basic[4]))
bugs2[3, 4] = as.integer(round(ci_all_enabled_disabled$basic[5]))


## Pair-Wise
funcao_bootstrap_pair_wise <- function(data, indexes){
  return(fbs_general(data, indexes, "alg_pair_wise"))
}

bootstraps_pair_wise <- boot(data = bugs, 
                   statistic = funcao_bootstrap_pair_wise,
                   R = 2000)

ci_pair_wise = boot.ci(boot.out = bootstraps_pair_wise, conf = 0.95, type = "basic")

bugs2[4, 3] = as.integer(round(ci_pair_wise$basic[4]))
bugs2[4, 4] = as.integer(round(ci_pair_wise$basic[5]))


bugs2 %>% 
  ggplot(aes(x = variable, y = value)) +
  geom_bar(stat = "identity", fill="pink")  +
  geom_errorbar(aes(ymin = ci_min,
                    ymax = ci_max), 
                width = 0.4, 
                position = position_dodge(width = 0.8)) +
  labs(title = "Bugs detectados por cada algoritmo",
       x = "algoritmos", y = "quantidade de bugs")
```
